### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by nZambi-** [robinp7720/Oblecto#12]
fatal error C1083: Cannot open include file: 'dns_sd.h' : No such file or directory
During npm install it is stumbling on the above fatal error. A quick web search shows this is possibly a dependency on Apples Bonjour SDK. If so, how does one install on PC without an Apple Developer account? 

Win10
Bonjour PS installed

**Comment by robinp7720** [comment]
I you pull the repo again, there should be a config option to disable mdns.
