### ISSUE TITLE
Replace all uses of jimp with sharp

### ISSUE THREAD

**Issue by robinp7720** [robinp7720/Oblecto#34]
Jimp should be removed as a dependency as sharp is already a dependency anyways and it far more performant.
All uses of jimp should be migrated to sharp.

**Comment by hamptonmoore** [comment]
Should this be done using the ImageScaler class?

**Comment by robinp7720** [comment]
This primarily concerns https://github.com/robinp7720/Oblecto/blob/83762dbafbbb175e889be7ade7462c34c1a6f6a3/src/submodules/REST/routes/movies.js#L119, https://github.com/robinp7720/Oblecto/blob/83762dbafbbb175e889be7ade7462c34c1a6f6a3/src/submodules/REST/routes/tvshows.js#L95 and https://github.com/robinp7720/Oblecto/blob/83762dbafbbb175e889be7ade7462c34c1a6f6a3/src/submodules/REST/routes/episodes.js#L78 which jimp is used to verify the image aspect ratio; to prevent banners from being uploaded as posters.

The rescaleImage job should be called on the queue to rescale the uploaded image to configured image sizes

**Comment by hamptonmoore** [comment]
My apologies I should've looked closer at the codebase, I'll fix this issue tonight
