### ISSUE TITLE
Propose logo

### ISSUE THREAD

**Issue by dee-y** [robinp7720/Oblecto#4]
Hello @robinp7720, i am a graphic designer. I would like to know if you would be interested in me making a logo for this project. If you would have me, i would make a logo for you, and it's free.

**Comment by robinp7720** [comment]
Sure. If you show some designs for Oblecto I may use it.

**Comment by dee-y** [comment]
Hello @robinp7720 here is a design am proposing, any thoughts?....

The cloud represents the availability of the videos to be continued on another device, the "O" is for Oblecto, and the play symbol represents the media.

![oblecto-01](https://user-images.githubusercontent.com/36637989/41670742-03cfcc68-74ad-11e8-9035-e98e4ced066d.png)

**Comment by robinp7720** [comment]
That looks great! You can push the logos in a folder named "images" in a PR if you wish

**Comment by dee-y** [comment]
Hi @robinp7720, i have successfully created my first pull request :)
the logo files are in the folder named "images".

https://github.com/robinp7720/Oblecto/pull/5

I have also uploaded all editable logo files formats on google drive here for your download

https://drive.google.com/drive/folders/18vcZfBlwVMwx9R-1ytir_Ym2KSWCiAWx?usp=sharing

best regards,
Dee-y

**Comment by robinp7720** [comment]
Thank you for the images! I've added the logo to the readme and added a thank you for the logos aswell :)
