### ISSUE TITLE
Docker installation failed: No matching distribution found for babelfish>=0.6.0 (from guessit)

### ISSUE THREAD

**Issue by josephyimsss** [robinp7720/Oblecto#93]
<strong>Overview</strong>
While following the Install Using Docker guide, the captioned error showed up. I fixed it temporarily by using an older version of `guessit`.

<strong>Steps to reproduce</strong>
1. `git clone --recurse-submodules https://github.com/robinp7720/Oblecto.git`
2. `docker build -t oblecto .`

```
Step 5/13 : RUN pip3 install guessit
 ---> Running in abf1a43c41b8
Collecting guessit
[omitted]
Collecting babelfish>=0.6.0 (from guessit)
  Could not find a version that satisfies the requirement babelfish>=0.6.0 (from guessit) (from versions: 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5)
No matching distribution found for babelfish>=0.6.0 (from guessit)
The command '/bin/sh -c pip3 install guessit' returned a non-zero code: 1
```

<strong>Possible reason</strong>
[`guessit`](https://pypi.org/project/guessit/) added `babelfish>=0.6.0` as dependency in v3.4.2, however [`babelfish==0.6.0`](https://pypi.org/project/babelfish/#description) requires at least Python 3.6, which is higher than the Python version in the `node:10` docker image

<strong>Temporary fix</strong>
Use previous `guessit` version by changing `RUN pip3 install guessit` to `RUN pip3 install guessit==3.4.1` in the `Dockerfile`

**Comment by robinp7720** [comment]
PR #98 should fix this. There is no reason to be using such an old version of nodejs. Could you please give it a try?

**Comment by josephyimsss** [comment]
Yes, it's working now. Thanks!
